### PR TITLE
Feature/main/rbac

### PR DESCRIPTION
**Pull request by kikeztw**
refactoring of the rules, this new flow allows adding roles and permissions in a more strict way

Note: the redme still needs to be updated
see test file for full example

```ts
const rules = new Rules();

  rules.role('admin').permission('dashboard').can(true, 'Access granted');
  rules .role('manager')
    .permission('dashboard')
    .dynamic((data: any) => {
      const result = data.id === testData.id;
      const message = result ? 'Access granted' : 'Access denied';
      return [result, message];
    });

rules.check('admin', 'dashboard')
```

### CODE REVIEW

**Comment by alacret** [comment]
@jesusrodrz @Rodasac please take a look at this, this is how we are gonna work permissions in the application

**Comment by kikeztw** [comment]
> @jesusrodrz @Rodasac please take a look at this, this is how we are gonna work permissions in the application

 ```js
const RBACproject = new RBAC();

 // defined the rules
RBACproject.createRule('admin', 'dashboard', true, 'Access granted');
RBACproject.createRule('manager', 'dashboard', false, 'Access denied');

 
 RBACproject.check('admin', 'dashboard') // [true, 'Access granted']
```

**Comment by kikeztw** [comment]
> > @jesusrodrz @Rodasac please take a look at this, this is how we are gonna work permissions in the application
> @alacret  this is ready
> ```js
> const RBACproject = new RBAC();
> 
> // defined the rules
> RBACproject.createRule('admin', 'dashboard', true, 'Access granted');
> RBACproject.createRule('manager', 'dashboard', false, 'Access denied');
> 
> 
> RBACproject.check('admin', 'dashboard') // [true, 'Access granted']
> ```

**Comment by jesusrodrz** [comment]
We should define what type convention use with enums 

This
```ts

enum Roles {
	ADMIN = "ADMIN"
}
enum Permissions = {
	DASHBOARD = "DASHBOARD"
}
​

const rules = new <typeof Roles, typeof Permissions>RBAC()
​
```

Or this 

```ts

enum Roles {
	ADMIN = "ADMIN"
}
enum Permissions = {
	DASHBOARD = "DASHBOARD"
}
​
// esta es otra
const rules = new <Roles,Permissions>RBAC()
```

the diference is that in fist case the type is mapped to `Records<keyof Enum,string>`

and the second is mapped to a string of the keys from the enum

**Comment by alacret** [comment]
@jesusrodrz @kikeztw 2nd one

**Review by jesusrodrz — APPROVED** [review]

**Review by alacret — APPROVED** [review]

**Pull request merged**
